name: Code Quality flows  # Workflow name

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
          
  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Print GitHub Token and Username
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "GitHub Token: $GITHUB_TOKEN"
          echo "Username: $USERNAME"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: List all files in the directory
        run: |
          echo "Listing all files in the directory"
          ls

      - name: Run a Bash Script
        run: bash num_count.sh