name: Code Quality flows  # Workflow name

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
          
  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Print GitHub Token and Username
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "GitHub Token: $GITHUB_TOKEN"
          echo "Username: $USERNAME"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: List all files in the directory
        run: |
          echo "Listing all files in the directory"
          tree -a

      - name: Enter the week3 folder
        working-directory: TDI_week7/TDI_week3
        run: echo "Entered TDI_week7/TDI_week3 directory"

      - name: Make all scripts executable
        working-directory: TDI_week7/TDI_week3
        run: chmod +x arguments.sh input_user_login.sh pwd_user_validate.sh file_creation.sh math_operation.sh

      - name: Run script arguments.sh
        working-directory: TDI_week7/TDI_week3
        run: ./arguments.sh

      - name: Run script input_user_login.sh
        working-directory: TDI_week7/TDI_week3
        run: ./input_user_login.sh

      - name: Run script pwd_user_validate.sh
        working-directory: TDI_week7/TDI_week3
        run: ./pwd_user_validate.sh
